### ISSUE TITLE
register package with PyPI

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/gemviz#101]
register package with [PyPI](https://pypi.org/) for installation by `pip install gemviz`

**Comment by prjemian** [comment]
To [upload to PyPI](https://github.com/pypa/gh-action-pypi-publish) from a GHA workflow (such as in [apstools](https://github.com/BCDA-APS/apstools/blob/main/.github/workflows/upload-pypi.yml)), we must create a repository token for PyPI to use, so it accepts new package builds from our GHA workflow.  This code in the workflow does the upload (here, it uses the name `PYPI_API_TOKEN `):

```yaml
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
```
